export { fork } from './createPipeKit';
export { latest } from './createPipeKit';
export { leading } from './createPipeKit';
export { once } from './createPipeKit';
export { extendedDebugInstruction as debug } from './debug';
export type { ForkInstruction } from './entities';
export type { LatestInstruction } from './entities';
export type { LeadingInstruction } from './entities';
export type { OnceInstruction } from './entities';
export type { DebugInstruction } from './entities';
export type { DisplayNameInstruction } from './entities';
export { DEBUG_INSTRUCTION_TYPE } from './entities';
export { DISPLAY_NAME_INSTRUCTION_TYPE } from './entities';
export { createDisplayNameInstruction as dn } from './instruction';
